const mongoose = require('mongoose');

const BloodRequestSchema = new mongoose.Schema({
  // Unique ID for the request (can be auto-generated by MongoDB, or a custom one if needed)
  requestId: {
    type: String,
    unique: true,
    trim: true,
    // You might auto-generate this in your backend route if not provided by frontend
  },
  // Reference to the Hospital making the request (made optional for doctors)
  hospital: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User', // Refers to the 'User' model (assuming Hospital is a User role)
    required: false, // <-- CHANGED TO FALSE
    default: null,   // <-- ADDED THIS LINE
  },
  // Reference to the Doctor associated with the request (optional)
  doctor: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User', // Refers to the 'User' model (assuming Doctor is a User role)
    default: null, // <-- ADDED THIS LINE
  },
  // Details of the blood requested
  bloodGroup: {
    type: String,
    required: true,
    enum: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
  },
  componentType: {
    type: String,
    required: true,
    enum: ['Whole Blood', 'Red Blood Cells', 'Plasma', 'Platelets', 'Cryoprecipitate'],
  },
  quantity: {
    type: Number,
    required: true,
    min: [1, 'Quantity must be at least 1 unit'],
  },
  urgency: {
    type: String,
    required: true,
    enum: ['Normal', 'Urgent', 'Emergency'],
    default: 'Normal',
  },
  // Status of the request
  status: {
    type: String,
    required: true,
    enum: ['Pending', 'Approved', 'Rejected', 'Fulfilled', 'Cancelled'],
    default: 'Pending',
  },
  // Date when the request was made
  requestDate: {
    type: Date,
    default: Date.now,
  },
  // Date when the request was fulfilled (if applicable)
  fulfillmentDate: {
    type: Date,
    default: null,
  },
  // Array of blood units assigned to this request (if fulfilled)
  assignedUnits: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'BloodUnit', // Refers to the 'BloodUnit' model
  }],
  notes: {
    type: String,
    trim: true,
  },
}, {
  timestamps: true // Adds createdAt and updatedAt fields
});

// Create the BloodRequest Model
const BloodRequest = mongoose.model('BloodRequest', BloodRequestSchema);

module.exports = BloodRequest;
